### PR TITLE
Test for merging after refactor

### PR DESCRIPTION
**Pull request by dingwentao**
@jtian0 Can you solve the conflict that causes the automatic merge failed? It seems to be a simple fix.

### CODE REVIEW

**Comment by jtian0** [comment]
> @jtian0 @wenyugai Any reason for these two new commits (mainly the refactor one) causes the automatic merge failed?

Should be header change. I am on rebasing `feature/nvcomp` and making submodules.

**Comment by jtian0** [comment]
> @jtian0 Can you solve the conflict that causes the automatic merge failed? It seems to be a simple fix.

I need make submodule before merge. Fixing header inclusion is of minimal work.

**Comment by dingwentao** [comment]
> > @jtian0 Can you solve the conflict that causes the automatic merge failed? It seems to be a simple fix.
> 
> I need make submodule before merge. Fixing header inclusion is of minimal work.

Sounds good, thanks. Please keep checking whether there will be a conflict to block our final merge (from master to nvcomp branch) when you push a new commit.

**Comment by jtian0** [comment]
> > > @jtian0 Can you solve the conflict that causes the automatic merge failed? It seems to be a simple fix.
> > 
> > 
> > I need make submodule before merge. Fixing header inclusion is of minimal work.
> 
> Sounds good, thanks. Please keep checking whether there will be a conflict to block our final merge (from master to nvcomp branch) when you push a new commit.

How does GitHub work when I turn this pull request to a draft? Is it a merge by branch, _regardless of specific commit_, rather than branch+commit?

By the way, https://github.com/szcompressor/cuSZ/commit/aae13799d1773450e95a96e8a5ebb113ec4a13f4 and https://github.com/szcompressor/cuSZ/commit/b8beddc7b47be651f0bec512b70564291a3f3afb are to modularize utils code snippets (i.e. can be used elsewhere, carrying minimal dependency), if not necessarily creating a new repo.

**Comment by dingwentao** [comment]
> > > > @jtian0 Can you solve the conflict that causes the automatic merge failed? It seems to be a simple fix.
> > > 
> > > 
> > > I need make submodule before merge. Fixing header inclusion is of minimal work.
> > 
> > 
> > Sounds good, thanks. Please keep checking whether there will be a conflict to block our final merge (from master to nvcomp branch) when you push a new commit.
> 
> How does GitHub work when I turn this pull request to a draft? Is it a merge request by branch, _regardless of specific commit_, rather than branch+commit?
> 
> By the way, [aae1379](https://github.com/szcompressor/cuSZ/commit/aae13799d1773450e95a96e8a5ebb113ec4a13f4) and [b8beddc](https://github.com/szcompressor/cuSZ/commit/b8beddc7b47be651f0bec512b70564291a3f3afb) are to modularize utils code snippets (i.e. can be used elsewhere, carrying minimal dependency), if not necessarily creating a new repo.

Based on my previous experience, it should be only based branch (I could be wrong). My story is when I created a pull request to push my own commits to the main branch, the repo admin asked me to fix something. After I fixed, I didn't need to recreate a new pull request but just used the old one with my fixed new commit. You can have a quick try to fix this conflict issue and see if it will reflect here.

**Comment by jtian0** [comment]
@dingwentao @wenyugai 
- I tested (using docker) and confirmed that not all tool combinations are working for `nvcomp` and/or `cub`. Please refer to [this repo](https://github.com/jtian0/precompiled-exolibs).
- With worry, `cmake -S <src> -B <build>` works only for pretty new "modern" cmake (e.g. `3.16`), as is seen in 
https://github.com/szcompressor/cuSZ/blob/d4ddb0e9d22196129f5b34388822e08e929c4303/Makefile#L108
For not-so-up2date (but probably largely available) version, such as `3.10`, a workaround can be  
  ```bash
  mkdir $(CMAKE_BUILD) && cd $(CMAKE_BUILD) && $(NVCOMP_CMAKE_HEAD) .. && make -j
  ``` 
  See the full context in [here](https://github.com/jtian0/precompiled-exolibs/blob/ca9230d25672cd138dea746b6d459a90f9a6c8af/Makefile#L23). (It does not display external repo perm. link.)
- I also [precompiled](https://github.com/jtian0/precompiled-exolibs/tree/main/precompiled) the `libnvcomp` and hopefully it (works in terms of ABI compatibility and) helps skip long compilation from the beginning, when using/testing/CI'ing.

**Pull request closed without merging**
